name: PSScriptAnalyzer
on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run PSScriptAnalyzer
        uses: -psscriptanalyzer-action
        with:
          path: .\
          recurse: true 
          output: results.sarif