name: PSScriptAnalyzer
on: [pull_request]

jobs:
  pester-test:
    name: PowerShell Script Analyzer
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run PSScriptAnalyzer
        # https://github.com/devblackops/github-action-psscriptanalyzer
        uses: devblackops/github-action-psscriptanalyzer@master
        with:
          sendComment: true
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          failOnErrors: true
          failOnWarnings: true
